<a href="https://colab.research.google.com/github/Riturajkumari/skills_basic_python/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.**

In [ ]:
import numpy as np

list_ = [ 1,2,3,4,5 ]

array_list = np.array(object = list_)
array_list

array([1, 2, 3, 4, 5])

In [ ]:
list_

[1, 2, 3, 4, 5]

In [ ]:
type(array_list)

numpy.ndarray

In [ ]:
type(list_)

list

**Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.**

In [ ]:
array_list

array([1, 2, 3, 4, 5])

In [ ]:
list_

[1, 2, 3, 4, 5]

In [ ]:
type(array_list)

numpy.ndarray

In [ ]:
type(list_)

list

**Q3. Considering the following changes in the variable, array_list:**

**array_list = np.array(object = list_, dtype = int)**

In [ ]:
array_list = np.array(object = list_, dtype = int)

In [ ]:
array_list

array([1, 2, 3, 4, 5])

In [ ]:
# Print the dtype
print(array_list.dtype)

int32


In [ ]:
# change the dtype to 'float64'
arr = array_list.astype('float32')

# Print the array after changing
# the data type
print(arr)

# Also print the data type
print(arr.dtype)


[1. 2. 3. 4. 5.]
float32


Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [ ]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)




In [ ]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [ ]:
#shape 
num_array.shape

(2, 3)

In [ ]:
# size 
num_array.ndim

2

**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.**

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [ ]:
# numpy.zeros method
c = np.zeros([3, 3])
print("\nMatrix c : \n", c)


Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
c.shape

(3, 3)

**Q6. Create an identity matrix of shape (5,5) using numpy functions?**

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [ ]:
# Python Programming illustrating
# numpy.identity method

import numpy as np



a = np.identity(5)
print("\nMatrix a : \n", a)



Matrix a : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a.shape

(5, 5)